[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my-app"
version = "0.1.0"
description = "Minimal example to reproduce flat layout packaging error"

[tool.setuptools]
packages = ["dags", "ddl", "deprecated"]  # Explicitly list your packages